small fix2

diff --git a/.github/workflows/pipeline.yaml b/.github/workflows/pipeline.yaml
--- a/.github/workflows/pipeline.yaml
+++ b/.github/workflows/pipeline.yaml
@@ -1,60 +1,49 @@
 name: Chat App Pipeline
 
 on:
-  push:
-    branches: [main]
-  pull_request:
-    branches: [main]
+ push:
+   branches: [main]
+ pull_request:
+   branches: [main]
 
 jobs:
-  build:
-    runs-on: ubuntu-latest
-    steps:
-      - name: checkout_code
-        uses: actions/checkout@v4
-      
-      - name: setup Node.js
-        uses: actions/setup-node@v4
-        with:
-          node-version: '18'
+ build:
+   runs-on: ubuntu-latest
+   steps:
+     - name: checkout_code
+       uses: actions/checkout@v4
+     
+     - name: setup Node.js
+       uses: actions/setup-node@v4
+       with:
+         node-version: '18'
 
-      - name: Test client
-        run: |
-          cd client
-          npm install
-          npm test -- --watchAll=false --passWithNoTests
+     - name: Test client
+       run: |
+         cd client
+         npm install
+         npm test -- --watchAll=false --passWithNoTests
 
-      - name: Test server
-        run: |
-          cd server
-          npm install
-          node -c index.js
+     - name: Test server
+       run: |
+         cd server
+         npm install
+         node -c index.js
 
-      - name: install docker-compose
-        uses:
-          docker/setup-buildx-action@v3
+     - name: Set up Docker
+       uses: docker/setup-buildx-action@v3
 
-      - name: Debug-check containers
-        run: |
-          docker compose ps
-          docker compose logs
+     - name: build and deploy
+       run: |
+         docker compose up --build -d
 
+     - name: Debug-check containers
+       run: |
+         docker compose ps
+         docker compose logs
 
-      - name: build and deploy
-        run: |
-          docker compose up --build -d
-
-      - name: Test deployed App
-        run: |
-          sleep 20
-          curl http://localhost:3000
-          curl http://localhost:3001
-          
-
-
-
-
-
-    
-
-        
+     - name: Test deployed App
+       run: |
+         sleep 30
+         curl http://localhost:3000
+         curl http://localhost:3001 || echo "Server connection failed"
